# Generated by Django 2.1.4 on 2020-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('publish', models.CharField(max_length=30)),
                ('antuor', models.CharField(max_length=30)),
                ('pub_date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
