# Generated by Django 2.1.4 on 2020-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='antuor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
